// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.1
// source: proto/menu.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RestaurantInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestaurantInfo) Reset() {
	*x = RestaurantInfo{}
	mi := &file_proto_menu_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestaurantInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestaurantInfo) ProtoMessage() {}

func (x *RestaurantInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_menu_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestaurantInfo.ProtoReflect.Descriptor instead.
func (*RestaurantInfo) Descriptor() ([]byte, []int) {
	return file_proto_menu_proto_rawDescGZIP(), []int{0}
}

func (x *RestaurantInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RestaurantInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RestaurantInfo) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type Category struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Order         int32                  `protobuf:"varint,3,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Category) Reset() {
	*x = Category{}
	mi := &file_proto_menu_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_proto_menu_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_proto_menu_proto_rawDescGZIP(), []int{1}
}

func (x *Category) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Category) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Category) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

type Dish struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	IsAvailable   bool                   `protobuf:"varint,5,opt,name=is_available,json=isAvailable,proto3" json:"is_available,omitempty"`
	CategoryId    int32                  `protobuf:"varint,6,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dish) Reset() {
	*x = Dish{}
	mi := &file_proto_menu_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dish) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dish) ProtoMessage() {}

func (x *Dish) ProtoReflect() protoreflect.Message {
	mi := &file_proto_menu_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dish.ProtoReflect.Descriptor instead.
func (*Dish) Descriptor() ([]byte, []int) {
	return file_proto_menu_proto_rawDescGZIP(), []int{2}
}

func (x *Dish) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Dish) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Dish) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Dish) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Dish) GetIsAvailable() bool {
	if x != nil {
		return x.IsAvailable
	}
	return false
}

func (x *Dish) GetCategoryId() int32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_menu_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_menu_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_menu_proto_rawDescGZIP(), []int{3}
}

type FullMenuResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RestaurantInfo *RestaurantInfo        `protobuf:"bytes,1,opt,name=restaurant_info,json=restaurantInfo,proto3" json:"restaurant_info,omitempty"`
	Categories     []*CategoryWithDishes  `protobuf:"bytes,2,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FullMenuResponse) Reset() {
	*x = FullMenuResponse{}
	mi := &file_proto_menu_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FullMenuResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FullMenuResponse) ProtoMessage() {}

func (x *FullMenuResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_menu_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FullMenuResponse.ProtoReflect.Descriptor instead.
func (*FullMenuResponse) Descriptor() ([]byte, []int) {
	return file_proto_menu_proto_rawDescGZIP(), []int{4}
}

func (x *FullMenuResponse) GetRestaurantInfo() *RestaurantInfo {
	if x != nil {
		return x.RestaurantInfo
	}
	return nil
}

func (x *FullMenuResponse) GetCategories() []*CategoryWithDishes {
	if x != nil {
		return x.Categories
	}
	return nil
}

type CategoryWithDishes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryInfo  *Category              `protobuf:"bytes,1,opt,name=category_info,json=categoryInfo,proto3" json:"category_info,omitempty"`
	Dishes        []*Dish                `protobuf:"bytes,2,rep,name=dishes,proto3" json:"dishes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryWithDishes) Reset() {
	*x = CategoryWithDishes{}
	mi := &file_proto_menu_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryWithDishes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryWithDishes) ProtoMessage() {}

func (x *CategoryWithDishes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_menu_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryWithDishes.ProtoReflect.Descriptor instead.
func (*CategoryWithDishes) Descriptor() ([]byte, []int) {
	return file_proto_menu_proto_rawDescGZIP(), []int{5}
}

func (x *CategoryWithDishes) GetCategoryInfo() *Category {
	if x != nil {
		return x.CategoryInfo
	}
	return nil
}

func (x *CategoryWithDishes) GetDishes() []*Dish {
	if x != nil {
		return x.Dishes
	}
	return nil
}

type ListCategoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []*Category            `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCategoriesResponse) Reset() {
	*x = ListCategoriesResponse{}
	mi := &file_proto_menu_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoriesResponse) ProtoMessage() {}

func (x *ListCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_menu_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoriesResponse.ProtoReflect.Descriptor instead.
func (*ListCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_proto_menu_proto_rawDescGZIP(), []int{6}
}

func (x *ListCategoriesResponse) GetCategories() []*Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

type ListDishesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dishes        []*Dish                `protobuf:"bytes,1,rep,name=dishes,proto3" json:"dishes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDishesResponse) Reset() {
	*x = ListDishesResponse{}
	mi := &file_proto_menu_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDishesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDishesResponse) ProtoMessage() {}

func (x *ListDishesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_menu_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDishesResponse.ProtoReflect.Descriptor instead.
func (*ListDishesResponse) Descriptor() ([]byte, []int) {
	return file_proto_menu_proto_rawDescGZIP(), []int{7}
}

func (x *ListDishesResponse) GetDishes() []*Dish {
	if x != nil {
		return x.Dishes
	}
	return nil
}

type CategoryID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryID) Reset() {
	*x = CategoryID{}
	mi := &file_proto_menu_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryID) ProtoMessage() {}

func (x *CategoryID) ProtoReflect() protoreflect.Message {
	mi := &file_proto_menu_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryID.ProtoReflect.Descriptor instead.
func (*CategoryID) Descriptor() ([]byte, []int) {
	return file_proto_menu_proto_rawDescGZIP(), []int{8}
}

func (x *CategoryID) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DishID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DishID) Reset() {
	*x = DishID{}
	mi := &file_proto_menu_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DishID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DishID) ProtoMessage() {}

func (x *DishID) ProtoReflect() protoreflect.Message {
	mi := &file_proto_menu_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DishID.ProtoReflect.Descriptor instead.
func (*DishID) Descriptor() ([]byte, []int) {
	return file_proto_menu_proto_rawDescGZIP(), []int{9}
}

func (x *DishID) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_proto_menu_proto protoreflect.FileDescriptor

const file_proto_menu_proto_rawDesc = "" +
	"\n" +
	"\x10proto/menu.proto\x12\x04menu\"T\n" +
	"\x0eRestaurantInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\"D\n" +
	"\bCategory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05order\x18\x03 \x01(\x05R\x05order\"\xa6\x01\n" +
	"\x04Dish\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12!\n" +
	"\fis_available\x18\x05 \x01(\bR\visAvailable\x12\x1f\n" +
	"\vcategory_id\x18\x06 \x01(\x05R\n" +
	"categoryId\"\a\n" +
	"\x05Empty\"\x8b\x01\n" +
	"\x10FullMenuResponse\x12=\n" +
	"\x0frestaurant_info\x18\x01 \x01(\v2\x14.menu.RestaurantInfoR\x0erestaurantInfo\x128\n" +
	"\n" +
	"categories\x18\x02 \x03(\v2\x18.menu.CategoryWithDishesR\n" +
	"categories\"m\n" +
	"\x12CategoryWithDishes\x123\n" +
	"\rcategory_info\x18\x01 \x01(\v2\x0e.menu.CategoryR\fcategoryInfo\x12\"\n" +
	"\x06dishes\x18\x02 \x03(\v2\n" +
	".menu.DishR\x06dishes\"H\n" +
	"\x16ListCategoriesResponse\x12.\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2\x0e.menu.CategoryR\n" +
	"categories\"8\n" +
	"\x12ListDishesResponse\x12\"\n" +
	"\x06dishes\x18\x01 \x03(\v2\n" +
	".menu.DishR\x06dishes\"\x1c\n" +
	"\n" +
	"CategoryID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\x18\n" +
	"\x06DishID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id2\xc8\x04\n" +
	"\vMenuService\x122\n" +
	"\vGetFullMenu\x12\v.menu.Empty\x1a\x16.menu.FullMenuResponse\x126\n" +
	"\x11GetRestaurantInfo\x12\v.menu.Empty\x1a\x14.menu.RestaurantInfo\x12B\n" +
	"\x14UpdateRestaurantInfo\x12\x14.menu.RestaurantInfo\x1a\x14.menu.RestaurantInfo\x120\n" +
	"\x0eCreateCategory\x12\x0e.menu.Category\x1a\x0e.menu.Category\x12;\n" +
	"\x0eListCategories\x12\v.menu.Empty\x1a\x1c.menu.ListCategoriesResponse\x120\n" +
	"\x0eUpdateCategory\x12\x0e.menu.Category\x1a\x0e.menu.Category\x12/\n" +
	"\x0eDeleteCategory\x12\x10.menu.CategoryID\x1a\v.menu.Empty\x12$\n" +
	"\n" +
	"CreateDish\x12\n" +
	".menu.Dish\x1a\n" +
	".menu.Dish\x12B\n" +
	"\x14ListDishesByCategory\x12\x10.menu.CategoryID\x1a\x18.menu.ListDishesResponse\x12$\n" +
	"\n" +
	"UpdateDish\x12\n" +
	".menu.Dish\x1a\n" +
	".menu.Dish\x12'\n" +
	"\n" +
	"DeleteDish\x12\f.menu.DishID\x1a\v.menu.EmptyB\x17Z\x15restaurant-menu/protob\x06proto3"

var (
	file_proto_menu_proto_rawDescOnce sync.Once
	file_proto_menu_proto_rawDescData []byte
)

func file_proto_menu_proto_rawDescGZIP() []byte {
	file_proto_menu_proto_rawDescOnce.Do(func() {
		file_proto_menu_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_menu_proto_rawDesc), len(file_proto_menu_proto_rawDesc)))
	})
	return file_proto_menu_proto_rawDescData
}

var file_proto_menu_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_menu_proto_goTypes = []any{
	(*RestaurantInfo)(nil),         // 0: menu.RestaurantInfo
	(*Category)(nil),               // 1: menu.Category
	(*Dish)(nil),                   // 2: menu.Dish
	(*Empty)(nil),                  // 3: menu.Empty
	(*FullMenuResponse)(nil),       // 4: menu.FullMenuResponse
	(*CategoryWithDishes)(nil),     // 5: menu.CategoryWithDishes
	(*ListCategoriesResponse)(nil), // 6: menu.ListCategoriesResponse
	(*ListDishesResponse)(nil),     // 7: menu.ListDishesResponse
	(*CategoryID)(nil),             // 8: menu.CategoryID
	(*DishID)(nil),                 // 9: menu.DishID
}
var file_proto_menu_proto_depIdxs = []int32{
	0,  // 0: menu.FullMenuResponse.restaurant_info:type_name -> menu.RestaurantInfo
	5,  // 1: menu.FullMenuResponse.categories:type_name -> menu.CategoryWithDishes
	1,  // 2: menu.CategoryWithDishes.category_info:type_name -> menu.Category
	2,  // 3: menu.CategoryWithDishes.dishes:type_name -> menu.Dish
	1,  // 4: menu.ListCategoriesResponse.categories:type_name -> menu.Category
	2,  // 5: menu.ListDishesResponse.dishes:type_name -> menu.Dish
	3,  // 6: menu.MenuService.GetFullMenu:input_type -> menu.Empty
	3,  // 7: menu.MenuService.GetRestaurantInfo:input_type -> menu.Empty
	0,  // 8: menu.MenuService.UpdateRestaurantInfo:input_type -> menu.RestaurantInfo
	1,  // 9: menu.MenuService.CreateCategory:input_type -> menu.Category
	3,  // 10: menu.MenuService.ListCategories:input_type -> menu.Empty
	1,  // 11: menu.MenuService.UpdateCategory:input_type -> menu.Category
	8,  // 12: menu.MenuService.DeleteCategory:input_type -> menu.CategoryID
	2,  // 13: menu.MenuService.CreateDish:input_type -> menu.Dish
	8,  // 14: menu.MenuService.ListDishesByCategory:input_type -> menu.CategoryID
	2,  // 15: menu.MenuService.UpdateDish:input_type -> menu.Dish
	9,  // 16: menu.MenuService.DeleteDish:input_type -> menu.DishID
	4,  // 17: menu.MenuService.GetFullMenu:output_type -> menu.FullMenuResponse
	0,  // 18: menu.MenuService.GetRestaurantInfo:output_type -> menu.RestaurantInfo
	0,  // 19: menu.MenuService.UpdateRestaurantInfo:output_type -> menu.RestaurantInfo
	1,  // 20: menu.MenuService.CreateCategory:output_type -> menu.Category
	6,  // 21: menu.MenuService.ListCategories:output_type -> menu.ListCategoriesResponse
	1,  // 22: menu.MenuService.UpdateCategory:output_type -> menu.Category
	3,  // 23: menu.MenuService.DeleteCategory:output_type -> menu.Empty
	2,  // 24: menu.MenuService.CreateDish:output_type -> menu.Dish
	7,  // 25: menu.MenuService.ListDishesByCategory:output_type -> menu.ListDishesResponse
	2,  // 26: menu.MenuService.UpdateDish:output_type -> menu.Dish
	3,  // 27: menu.MenuService.DeleteDish:output_type -> menu.Empty
	17, // [17:28] is the sub-list for method output_type
	6,  // [6:17] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_menu_proto_init() }
func file_proto_menu_proto_init() {
	if File_proto_menu_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_menu_proto_rawDesc), len(file_proto_menu_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_menu_proto_goTypes,
		DependencyIndexes: file_proto_menu_proto_depIdxs,
		MessageInfos:      file_proto_menu_proto_msgTypes,
	}.Build()
	File_proto_menu_proto = out.File
	file_proto_menu_proto_goTypes = nil
	file_proto_menu_proto_depIdxs = nil
}
